server:
  port: 8080
  servlet:
    context-path: /api

app:
  auth:
    refresh-token-cookie:
      name: refreshToken
      path: /api/auth
      secure: ${REFRESH_TOKEN_COOKIE_SECURE:false}
      same-site: lax

spring:
  application:
    name: bllsoneshot

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

init:
  mentor:
    login-id: ${INIT_MENTOR_LOGIN_ID:}
    password: ${INIT_MENTOR_PASSWORD:}
  mentee1:
    login-id: ${INIT_MENTEE1_LOGIN_ID:}
    password: ${INIT_MENTEE1_PASSWORD:}
  mentee2:
    login-id: ${INIT_MENTEE2_LOGIN_ID:}
    password: ${INIT_MENTEE2_PASSWORD:}

logging:
  level:
    org.hibernate.SQL: debug
