server:
  port: 8080
  servlet:
    context-path: /api

keys:
  jwt:
    secret: ${KEYS_JWT_SECRET}
    access-token-validity-in-milliseconds: ${KEYS_JWT_ACCESS_TOKEN_VALIDITY_IN_MILLISECONDS:3600000}

app:
  auth:
    refresh-token-cookie:
      name: refreshToken
      path: /api/auth
      secure: ${REFRESH_TOKEN_COOKIE_SECURE:false}
      same-site: lax
  file:
    max-bytes: ${APP_FILE_MAX_BYTES}

spring:
  application:
    name: bllsoneshot

  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

init:
  mentor:
    login-id: ${INIT_MENTOR_LOGIN_ID:mentor}
    password: ${INIT_MENTOR_PASSWORD:mentor123}
    name: ${INIT_MENTOR_NAME:기본멘토}
  mentee1:
    login-id: ${INIT_MENTEE1_LOGIN_ID:mentee1}
    password: ${INIT_MENTEE1_PASSWORD:mentee1}
    name: ${INIT_MENTEE1_NAME:기본멘티1}
  mentee2:
    login-id: ${INIT_MENTEE2_LOGIN_ID:mentee2}
    password: ${INIT_MENTEE2_PASSWORD:mentee2}
    name: ${INIT_MENTEE2_NAME:기본멘티2}

logging:
  level:
    org.hibernate.SQL: debug

aws:
  region: ${CLOUD_AWS_REGION:ap-northeast-2}
  credentials:
    access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
    secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
  s3:
    bucket: ${CLOUD_AWS_BUCKET}
    cdn-url: ${CLOUD_AWS_CDN_URL}